main: nullblade.craftanddeath.main.Main
version: 0.1.3
name: CraftAndDeath
author: nullBlade

commands:
  cgive:
    description: Gives custom item to player
    permission: craftAndDeath.give
    aliases: [cg]
    usage: /<command> <item>
  recipebook:
    description: Gives custom item to player
    permission: craftAndDeath.recipes
    aliases: [rb, crafts, craft, crafting, recipe, recipes, how_do_i_make_something]
    usage: /<command>
  customsummon:
    description: Summons custom entity at player's coordinates
    permission: craftAndDeath.recipes
    aliases: [ cs, csummon, entity ]
    usage: /<command>

permissions:
  craftAndDeath.default:
    description: default
    default: true
    children:
      craftAndDeath.recipes: true
